// src/app/layout.js
import "./globals.css";
import "./common.css";


import "swiper/css";
import "swiper/css/pagination";

// Add metadata here (good for SEO, works in Server Components)
export const metadata = {
  title: "My Next.js App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"
        />
      </head>
      <body>
        {children}
      
      </body>
    </html>
  );
}
